// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5638.frc56382018.subsystems;

import org.usfirst.frc5638.frc56382018.RobotMap;
import org.usfirst.frc5638.frc56382018.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.SpeedControllerGroup;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class driveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final WPI_VictorSPX victorSPXleft = RobotMap.driveTrainVictorSPXleft;
    private final WPI_TalonSRX talonSRXleft = RobotMap.driveTrainTalonSRXleft;
    private final SpeedControllerGroup leftGearbox = RobotMap.driveTrainleftGearbox;
    private final WPI_VictorSPX victorSPXright = RobotMap.driveTrainVictorSPXright;
    private final WPI_TalonSRX talonSRXright = RobotMap.driveTrainTalonSRXright;
    private final SpeedControllerGroup rightGearbox = RobotMap.driveTrainrightGearbox;
    private final DifferentialDrive driveTrain = RobotMap.driveTrainRobotDrive21;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        setDefaultCommand(new driveCom());
    }

    
    public void drive(Joystick xbox1) {
        // Put code here to be run every loop
    	double steerStick;
		steerStick = xbox1.getRawAxis(0);
		
		if(steerStick < .1 || steerStick > -.1) {
			steerStick = 0;
		}
		
		driveTrain.arcadeDrive((-xbox1.getRawAxis(2) + xbox1.getRawAxis(3)), xbox1.getRawAxis(0));
    }
    
    public void stop() {
    	driveTrain.arcadeDrive(0, 0);
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

