// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5638.frc56382018.subsystems;

import org.usfirst.frc5638.frc56382018.RobotMap;
import org.usfirst.frc5638.frc56382018.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.FeedbackDevice;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class dump extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final WPI_TalonSRX talonSRXdump = RobotMap.dumpTalonSRXdump;
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    
    public void dumpOut() {
        // Put code here to be run every loop
    	talonSRXdump.set(.25);
    	SmartDashboard.putNumber("dump position", talonSRXdump.getSelectedSensorPosition(0));
    }
    public void dumpIn() {
    	talonSRXdump.set(-.25);
    }
    public void stop() {
    	talonSRXdump.set(0);
    }
    
    public void dumpinPID() {
    	//talonSRXdump.setSelectedSensorPosition(118, 0, 10); //118 is the encoder position of resting
    	talonSRXdump.set(ControlMode.Position, 3000);
    }
    
    public void dumpoutPID() {
    	//talonSRXdump.setSelectedSensorPosition(2800, 0, 10); //2800 is encoder position of dumping
    	talonSRXdump.set(ControlMode.Position, -299);
    }
    
    public void dumpReset() {
    	talonSRXdump.setSelectedSensorPosition(0, 0, 10); //reset dump postition to 0
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

