// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5638.frc56382018;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.FeedbackDevice;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;
import edu.wpi.first.wpilibj.DoubleSolenoid;
//import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_VictorSPX driveTrainVictorSPXleft;
    public static WPI_TalonSRX driveTrainTalonSRXleft;
    public static SpeedControllerGroup driveTrainleftGearbox;
    public static WPI_VictorSPX driveTrainVictorSPXright;
    public static WPI_TalonSRX driveTrainTalonSRXright;
    public static SpeedControllerGroup driveTrainrightGearbox;
    public static DifferentialDrive driveTrainRobotDrive21;
    public static WPI_TalonSRX elevatorTalonSRXelevator;
    public static WPI_VictorSPX intakeTalonSRXintake2;
    public static WPI_VictorSPX intakeTalonSRXintake1;
    public static WPI_TalonSRX dumpTalonSRXdump;
    public static WPI_TalonSRX climberMotorsTalonSRXclimber1;
    public static WPI_TalonSRX climberMotorsTalonSRXclimber2;
    public static SpeedControllerGroup climberMotorsSpeedControllerGroup1;
    public static WPI_TalonSRX armTalonSRXarm;
    public static DoubleSolenoid intakeOCDoubleSolenoidintake;
    public static DoubleSolenoid shiftDoubleSolenoidshift;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        driveTrainTalonSRXleft = new WPI_TalonSRX(2);
        driveTrainTalonSRXleft.configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Relative, 0, 10);
        
        //driveTrainVictorSPXleft.set(ControlMode.Follower, 2);
        driveTrainVictorSPXleft = new WPI_VictorSPX(3);
        
        driveTrainleftGearbox = new SpeedControllerGroup(driveTrainTalonSRXleft, driveTrainVictorSPXleft  );
        //LiveWindow.addActuator("driveTrain", "leftGearbox", driveTrainleftGearbox);
        
        
        
        
        driveTrainTalonSRXright = new WPI_TalonSRX(4);
        driveTrainTalonSRXright.configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Relative, 0, 10);
        
        driveTrainVictorSPXright = new WPI_VictorSPX(5);
        //driveTrainVictorSPXright.set(ControlMode.Follower, 4);
        
        
        driveTrainrightGearbox = new SpeedControllerGroup(driveTrainTalonSRXright, driveTrainVictorSPXright  );
        //LiveWindow.addActuator("driveTrain", "rightGearbox", driveTrainrightGearbox);
        
        driveTrainRobotDrive21 = new DifferentialDrive(driveTrainleftGearbox, driveTrainrightGearbox);
        
        driveTrainRobotDrive21.setSafetyEnabled(true);
        driveTrainRobotDrive21.setExpiration(0.1);
        //driveTrainRobotDrive21.setSensitivity(0.5);
        driveTrainRobotDrive21.setMaxOutput(1.0);

        elevatorTalonSRXelevator = new WPI_TalonSRX(6);
        
        
        intakeTalonSRXintake2 = new WPI_VictorSPX(10);
        
        
        intakeTalonSRXintake1 = new WPI_VictorSPX(9);
        
        
        dumpTalonSRXdump = new WPI_TalonSRX(7);
        dumpTalonSRXdump.configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Relative, 0, 10);
        
        
        climberMotorsTalonSRXclimber1 = new WPI_TalonSRX(12);
        
        climberMotorsTalonSRXclimber1.setInverted(false);
        
        
        climberMotorsTalonSRXclimber2 = new WPI_TalonSRX(11);
        
        climberMotorsTalonSRXclimber2.setInverted(true);
        
        
        climberMotorsSpeedControllerGroup1 = new SpeedControllerGroup(climberMotorsTalonSRXclimber1, climberMotorsTalonSRXclimber2);
        //LiveWindow.addActuator("climberMotors", "Speed Controller Group 1", climberMotorsSpeedControllerGroup1);
        
        armTalonSRXarm = new WPI_TalonSRX(8);
        
        
        intakeOCDoubleSolenoidintake = new DoubleSolenoid(0, 2, 3);
        //LiveWindow.addActuator("intakeOC", "Double Solenoid intake", intakeOCDoubleSolenoidintake);
        
        shiftDoubleSolenoidshift = new DoubleSolenoid(0, 0, 1);
        //LiveWindow.addActuator("shift", "Double Solenoid shift", shiftDoubleSolenoidshift);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
